"""
backend/services/demo_service.py
Phase 11 — Live Model Comparison service.

Runs the same cybersecurity question through two models simultaneously
(synchronously via threading) using the same RAG evidence, then generates
a concise difference summary.

Design:
  - Retrieves RAG evidence once and shares it between both models.
  - Base model answer: uses base LLM (no domain adaptation).
  - Adapted model answer: uses models/adapted (if present); falls back to base.
  - Difference analysis: generated by the adapted model.
  - All results are honest — no score inflation.
"""

from __future__ import annotations

import concurrent.futures
import logging
import time
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# ── Pre-designed cybersecurity demonstration questions ────────────────────────

DEMO_QUESTIONS: list[dict] = [
    {
        "id": "q1",
        "category": "Vulnerability Analysis",
        "question": (
            "What is CVE-2021-44228 (Log4Shell), and what attack vector does it exploit?"
        ),
        "rationale": (
            "Log4Shell is a high-profile RCE vulnerability. Domain-adapted models "
            "should recognize JNDI injection and LDAP exploitation patterns."
        ),
    },
    {
        "id": "q2",
        "category": "Attack Technique",
        "question": (
            "Describe the MITRE ATT&CK technique T1059 (Command and Scripting Interpreter) "
            "and list three common sub-techniques adversaries use in Windows environments."
        ),
        "rationale": (
            "Tests knowledge of ATT&CK framework taxonomy and sub-technique enumeration."
        ),
    },
    {
        "id": "q3",
        "category": "Threat Intelligence",
        "question": (
            "What indicators of compromise (IoCs) would you look for after a suspected "
            "SQL injection attack on a web application?"
        ),
        "rationale": (
            "Assesses ability to enumerate IoCs including error patterns, "
            "abnormal query lengths, and WAF alerts."
        ),
    },
    {
        "id": "q4",
        "category": "Defensive Controls",
        "question": (
            "What OWASP Top 10 category covers broken access control, and what "
            "three controls can remediate it?"
        ),
        "rationale": (
            "Tests recall of OWASP A01:2021 and practical defensive countermeasures."
        ),
    },
    {
        "id": "q5",
        "category": "Incident Response",
        "question": (
            "An analyst detects unusual outbound DNS queries with base64-encoded subdomains "
            "at regular intervals. What threat category does this suggest, and what "
            "immediate containment steps should be taken?"
        ),
        "rationale": (
            "DNS tunneling / C2 exfiltration scenario. Tests domain-specific pattern "
            "recognition and IR playbook knowledge."
        ),
    },
]


# ── Helpers ───────────────────────────────────────────────────────────────────

def _get_adapted_model_path() -> Optional[str]:
    """Return the adapted model path if a checkpoint exists, else None."""
    adapted_dir = Path("models/adapted")
    # Accept a directory with config.json (HF format) or pytorch_model.bin
    if (adapted_dir / "config.json").exists():
        return str(adapted_dir)
    return None


def _retrieve_evidence(question: str, top_k: int = 3) -> tuple[list[dict], bool]:
    """Retrieve RAG evidence. Returns (sources_list, evidence_sufficient)."""
    try:
        from backend.services.rag_service import _ensure_loaded, _retriever
        _ensure_loaded(top_k=top_k)
        chunks, sufficient = _retriever.retrieve(question)
        sources = [
            {
                "source": c.source,
                "topic": c.topic,
                "document_type": c.document_type,
                "license": c.license,
                "score": c.score,
                "text_preview": c.text[:250].strip(),
            }
            for c in chunks
        ]
        return sources, sufficient
    except Exception as exc:
        logger.warning("RAG retrieval unavailable during comparison: %s", exc)
        return [], False


def _build_prompt(question: str, evidence_chunks: list[dict]) -> str:
    """Build a RAG-grounded prompt with the retrieved evidence."""
    from rag.retriever import build_rag_prompt

    # Reconstruct minimal chunk objects for prompt builder
    class _Chunk:
        def __init__(self, d: dict):
            self.text = d.get("text_preview", "")
            self.source = d.get("source", "")
            self.score = d.get("score", 0.0)

    chunks = [_Chunk(d) for d in evidence_chunks]
    try:
        return build_rag_prompt(
            question=question,
            chunks=chunks,  # type: ignore[arg-type]
            evidence_sufficient=bool(evidence_chunks),
        )
    except Exception:
        # Fallback to simple prompt if build_rag_prompt fails
        evidence_text = "\n\n".join(
            f"[{i+1}] {c.text}" for i, c in enumerate(chunks)
        ) if chunks else "No evidence retrieved."
        return (
            f"You are a cybersecurity expert.\n\n"
            f"Retrieved Evidence:\n{evidence_text}\n\n"
            f"Question: {question}\n\nAnswer:"
        )


def _generate(
    prompt: str,
    model_name: Optional[str],
    label: str,
    max_tokens: int = 200,
) -> dict:
    """Run generation for one model and return a structured result."""
    from backend.services.llm_service import generate_response, LLMServiceError

    t0 = time.perf_counter()
    try:
        result = generate_response(
            prompt=prompt,
            max_tokens=max_tokens,
            temperature=0.3,
            model_name=model_name,
        )
        return {
            "answer": result["response"],
            "model": result["model"],
            "latency_ms": result["latency_ms"],
            "error": None,
        }
    except LLMServiceError as exc:
        logger.warning("Generation failed for %s: %s", label, exc)
        return {
            "answer": f"[Model unavailable: {exc}]",
            "model": label,
            "latency_ms": round((time.perf_counter() - t0) * 1000, 2),
            "error": str(exc),
        }
    except Exception as exc:
        logger.exception("Unexpected error for %s: %s", label, exc)
        return {
            "answer": "[Generation error — check server logs]",
            "model": label,
            "latency_ms": round((time.perf_counter() - t0) * 1000, 2),
            "error": str(exc),
        }


def _generate_difference_summary(
    question: str,
    base_answer: str,
    adapted_answer: str,
    adapted_model: Optional[str],
) -> str:
    """Ask the adapted model to explain what differs between the two answers."""
    diff_prompt = (
        f"You are a cybersecurity AI evaluation assistant.\n\n"
        f"A question was answered by two AI models.\n\n"
        f"Question: {question}\n\n"
        f"Base Model Answer:\n{base_answer}\n\n"
        f"Adapted Model Answer:\n{adapted_answer}\n\n"
        f"In 2-4 sentences, explain what is different between these two answers. "
        f"Be factual and precise. If the answers are similar, say so clearly. "
        f"Do not claim one is better unless there is a measurable factual difference.\n\n"
        f"Difference Summary:"
    )
    from backend.services.llm_service import generate_response, LLMServiceError
    try:
        result = generate_response(
            prompt=diff_prompt,
            max_tokens=150,
            temperature=0.2,
            model_name=adapted_model,
        )
        return result["response"]
    except (LLMServiceError, Exception) as exc:
        logger.warning("Difference summary generation failed: %s", exc)
        return "Difference summary could not be generated."


# ── Public API ────────────────────────────────────────────────────────────────

def run_comparison(question: str, top_k: int = 3) -> dict:
    """
    Run a side-by-side comparison of base vs adapted model for the given question.

    Steps:
      1. Retrieve RAG evidence (shared between both models).
      2. Build a shared RAG-grounded prompt.
      3. Generate answers from base + adapted concurrently.
      4. Generate a difference summary.

    Returns a structured dict ready for the API response.
    """
    t_total = time.perf_counter()

    from backend.core.config import get_settings
    settings = get_settings()
    base_model_name = settings.base_model_name
    adapted_model_path = _get_adapted_model_path()

    logger.info(
        "Demo comparison | question=%.80s | base=%s | adapted=%s",
        question, base_model_name, adapted_model_path or "NOT_FOUND",
    )

    # ── Step 1: Retrieve shared RAG evidence ─────────────────────────────────
    sources, evidence_sufficient = _retrieve_evidence(question, top_k=top_k)

    # ── Step 2: Build shared prompt ───────────────────────────────────────────
    prompt = _build_prompt(question, sources)

    # ── Step 3: Generate from both models concurrently ────────────────────────
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        base_future = executor.submit(
            _generate, prompt, base_model_name, "Base Model"
        )
        adapted_future = executor.submit(
            _generate, prompt, adapted_model_path, "CyberAdapt-LLM"
        )
        base_result = base_future.result()
        adapted_result = adapted_future.result()

    # ── Step 4: Difference summary ────────────────────────────────────────────
    difference_summary = _generate_difference_summary(
        question=question,
        base_answer=base_result["answer"],
        adapted_answer=adapted_result["answer"],
        adapted_model=adapted_model_path or base_model_name,
    )

    total_latency_ms = round((time.perf_counter() - t_total) * 1000, 2)

    return {
        "question": question,
        "base": {
            "answer": base_result["answer"],
            "model": base_result["model"],
            "latency_ms": base_result["latency_ms"],
            "error": base_result["error"],
        },
        "adapted": {
            "answer": adapted_result["answer"],
            "model": adapted_result["model"],
            "adapted_model_available": adapted_model_path is not None,
            "latency_ms": adapted_result["latency_ms"],
            "error": adapted_result["error"],
        },
        "evidence": {
            "sources": sources,
            "evidence_sufficient": evidence_sufficient,
            "num_chunks": len(sources),
        },
        "difference_summary": difference_summary,
        "total_latency_ms": total_latency_ms,
        "disclaimer": (
            "This is a research demonstration. Both answers are generated by AI and may "
            "contain inaccuracies. Adapted model uses domain-trained weights if available."
        ),
    }
