"""backend/schemas/report.py — Schemas for POST /api/v1/report/generate"""
from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


class ReportRequest(BaseModel):
    incident_description: str = Field(
        ..., min_length=20, max_length=5000,
        description="Security incident description to generate a report for.",
    )
    affected_assets: list[str] = Field(
        default_factory=list,
        description="Optional list of affected assets (servers, applications, users).",
    )
    analyst_name: str = Field(default="CyberAdapt-LLM", description="Analyst name for report header.")
    organization: str = Field(default="[Organization]", description="Organization name.")
    top_k: int = Field(default=3, ge=1, le=10)

    model_config = {"json_schema_extra": {"example": {
        "incident_description": "Ransomware attack detected on file server FS-01. Encryption started at 03:14 UTC.",
        "affected_assets": ["FS-01", "BACKUP-01", "Domain Controller"],
        "analyst_name": "Security Team",
        "organization": "Acme Corp",
    }}}


class SecurityReport(BaseModel):
    report_id: str = Field(..., description="Unique report identifier.")
    generated_at: str = Field(..., description="ISO timestamp of generation.")
    analyst: str = Field(...)
    organization: str = Field(...)

    executive_summary: str = Field(..., description="Non-technical summary for executives.")
    threat_description: str = Field(..., description="Detailed threat description.")
    affected_assets: list[str] = Field(default_factory=list)
    indicators: list[str] = Field(default_factory=list, description="Indicators of Compromise.")
    risk_assessment: str = Field(..., description="Risk level and business impact.")
    mitre_mapping: list[str] = Field(default_factory=list, description="Relevant MITRE ATT&CK techniques.")
    recommendations: list[str] = Field(default_factory=list, description="Prioritised defensive recommendations.")
    evidence: list[dict] = Field(default_factory=list)
    limitations: str = Field(..., description="Analysis limitations and caveats.")

    confidence: str = Field(...)
    latency_ms: float = Field(...)
    model: str = Field(...)
    disclaimer: str = Field(
        default=(
            "This report is generated by an AI system for defensive analysis only. "
            "Verify all findings with qualified security professionals before taking action."
        )
    )
